// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/kiarashAlizadeh/herotech/internal/dto"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AuctionService is an autogenerated mock type for the AuctionService type
type AuctionService struct {
	mock.Mock
}

type AuctionService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuctionService) EXPECT() *AuctionService_Expecter {
	return &AuctionService_Expecter{mock: &_m.Mock}
}

// GetAuction provides a mock function with given fields: ctx, id
func (_m *AuctionService) GetAuction(ctx context.Context, id uuid.UUID) (*dto.AuctionResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAuction")
	}

	var r0 *dto.AuctionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.AuctionResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.AuctionResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AuctionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionService_GetAuction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuction'
type AuctionService_GetAuction_Call struct {
	*mock.Call
}

// GetAuction is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *AuctionService_Expecter) GetAuction(ctx interface{}, id interface{}) *AuctionService_GetAuction_Call {
	return &AuctionService_GetAuction_Call{Call: _e.mock.On("GetAuction", ctx, id)}
}

func (_c *AuctionService_GetAuction_Call) Run(run func(ctx context.Context, id uuid.UUID)) *AuctionService_GetAuction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AuctionService_GetAuction_Call) Return(_a0 *dto.AuctionResponse, _a1 error) *AuctionService_GetAuction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionService_GetAuction_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*dto.AuctionResponse, error)) *AuctionService_GetAuction_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveAuctions provides a mock function with given fields: ctx, req
func (_m *AuctionService) ListActiveAuctions(ctx context.Context, req dto.PaginationRequest) (*dto.PaginatedResponse[dto.AuctionResponse], error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveAuctions")
	}

	var r0 *dto.PaginatedResponse[dto.AuctionResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.PaginationRequest) (*dto.PaginatedResponse[dto.AuctionResponse], error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.PaginationRequest) *dto.PaginatedResponse[dto.AuctionResponse]); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PaginatedResponse[dto.AuctionResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.PaginationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionService_ListActiveAuctions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveAuctions'
type AuctionService_ListActiveAuctions_Call struct {
	*mock.Call
}

// ListActiveAuctions is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.PaginationRequest
func (_e *AuctionService_Expecter) ListActiveAuctions(ctx interface{}, req interface{}) *AuctionService_ListActiveAuctions_Call {
	return &AuctionService_ListActiveAuctions_Call{Call: _e.mock.On("ListActiveAuctions", ctx, req)}
}

func (_c *AuctionService_ListActiveAuctions_Call) Run(run func(ctx context.Context, req dto.PaginationRequest)) *AuctionService_ListActiveAuctions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.PaginationRequest))
	})
	return _c
}

func (_c *AuctionService_ListActiveAuctions_Call) Return(_a0 *dto.PaginatedResponse[dto.AuctionResponse], _a1 error) *AuctionService_ListActiveAuctions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionService_ListActiveAuctions_Call) RunAndReturn(run func(context.Context, dto.PaginationRequest) (*dto.PaginatedResponse[dto.AuctionResponse], error)) *AuctionService_ListActiveAuctions_Call {
	_c.Call.Return(run)
	return _c
}

// PlaceBid provides a mock function with given fields: ctx, auctionID, bidderID, req
func (_m *AuctionService) PlaceBid(ctx context.Context, auctionID uuid.UUID, bidderID uuid.UUID, req dto.PlaceBidRequest) error {
	ret := _m.Called(ctx, auctionID, bidderID, req)

	if len(ret) == 0 {
		panic("no return value specified for PlaceBid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.PlaceBidRequest) error); ok {
		r0 = rf(ctx, auctionID, bidderID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuctionService_PlaceBid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaceBid'
type AuctionService_PlaceBid_Call struct {
	*mock.Call
}

// PlaceBid is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID uuid.UUID
//   - bidderID uuid.UUID
//   - req dto.PlaceBidRequest
func (_e *AuctionService_Expecter) PlaceBid(ctx interface{}, auctionID interface{}, bidderID interface{}, req interface{}) *AuctionService_PlaceBid_Call {
	return &AuctionService_PlaceBid_Call{Call: _e.mock.On("PlaceBid", ctx, auctionID, bidderID, req)}
}

func (_c *AuctionService_PlaceBid_Call) Run(run func(ctx context.Context, auctionID uuid.UUID, bidderID uuid.UUID, req dto.PlaceBidRequest)) *AuctionService_PlaceBid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(dto.PlaceBidRequest))
	})
	return _c
}

func (_c *AuctionService_PlaceBid_Call) Return(_a0 error) *AuctionService_PlaceBid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuctionService_PlaceBid_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, dto.PlaceBidRequest) error) *AuctionService_PlaceBid_Call {
	_c.Call.Return(run)
	return _c
}

// StartAuction provides a mock function with given fields: ctx, sellerID, req
func (_m *AuctionService) StartAuction(ctx context.Context, sellerID uuid.UUID, req dto.CreateAuctionRequest) (*dto.AuctionResponse, error) {
	ret := _m.Called(ctx, sellerID, req)

	if len(ret) == 0 {
		panic("no return value specified for StartAuction")
	}

	var r0 *dto.AuctionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateAuctionRequest) (*dto.AuctionResponse, error)); ok {
		return rf(ctx, sellerID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateAuctionRequest) *dto.AuctionResponse); ok {
		r0 = rf(ctx, sellerID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AuctionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.CreateAuctionRequest) error); ok {
		r1 = rf(ctx, sellerID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionService_StartAuction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartAuction'
type AuctionService_StartAuction_Call struct {
	*mock.Call
}

// StartAuction is a helper method to define mock.On call
//   - ctx context.Context
//   - sellerID uuid.UUID
//   - req dto.CreateAuctionRequest
func (_e *AuctionService_Expecter) StartAuction(ctx interface{}, sellerID interface{}, req interface{}) *AuctionService_StartAuction_Call {
	return &AuctionService_StartAuction_Call{Call: _e.mock.On("StartAuction", ctx, sellerID, req)}
}

func (_c *AuctionService_StartAuction_Call) Run(run func(ctx context.Context, sellerID uuid.UUID, req dto.CreateAuctionRequest)) *AuctionService_StartAuction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(dto.CreateAuctionRequest))
	})
	return _c
}

func (_c *AuctionService_StartAuction_Call) Return(_a0 *dto.AuctionResponse, _a1 error) *AuctionService_StartAuction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionService_StartAuction_Call) RunAndReturn(run func(context.Context, uuid.UUID, dto.CreateAuctionRequest) (*dto.AuctionResponse, error)) *AuctionService_StartAuction_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuctionService creates a new instance of AuctionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuctionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuctionService {
	mock := &AuctionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
