// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kiarashAlizadeh/herotech/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// AuctionRepository is an autogenerated mock type for the AuctionRepository type
type AuctionRepository struct {
	mock.Mock
}

type AuctionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AuctionRepository) EXPECT() *AuctionRepository_Expecter {
	return &AuctionRepository_Expecter{mock: &_m.Mock}
}

// CancelBidTransaction provides a mock function with given fields: ctx, auctionID, bidderID
func (_m *AuctionRepository) CancelBidTransaction(ctx context.Context, auctionID uuid.UUID, bidderID uuid.UUID) error {
	ret := _m.Called(ctx, auctionID, bidderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelBidTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, auctionID, bidderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuctionRepository_CancelBidTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelBidTransaction'
type AuctionRepository_CancelBidTransaction_Call struct {
	*mock.Call
}

// CancelBidTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID uuid.UUID
//   - bidderID uuid.UUID
func (_e *AuctionRepository_Expecter) CancelBidTransaction(ctx interface{}, auctionID interface{}, bidderID interface{}) *AuctionRepository_CancelBidTransaction_Call {
	return &AuctionRepository_CancelBidTransaction_Call{Call: _e.mock.On("CancelBidTransaction", ctx, auctionID, bidderID)}
}

func (_c *AuctionRepository_CancelBidTransaction_Call) Run(run func(ctx context.Context, auctionID uuid.UUID, bidderID uuid.UUID)) *AuctionRepository_CancelBidTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AuctionRepository_CancelBidTransaction_Call) Return(_a0 error) *AuctionRepository_CancelBidTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuctionRepository_CancelBidTransaction_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *AuctionRepository_CancelBidTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, itemID, sellerID, startPrice, duration
func (_m *AuctionRepository) Create(ctx context.Context, itemID uuid.UUID, sellerID uuid.UUID, startPrice int64, duration time.Duration) (*domain.Auction, error) {
	ret := _m.Called(ctx, itemID, sellerID, startPrice, duration)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Auction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int64, time.Duration) (*domain.Auction, error)); ok {
		return rf(ctx, itemID, sellerID, startPrice, duration)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int64, time.Duration) *domain.Auction); ok {
		r0 = rf(ctx, itemID, sellerID, startPrice, duration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Auction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int64, time.Duration) error); ok {
		r1 = rf(ctx, itemID, sellerID, startPrice, duration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AuctionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID uuid.UUID
//   - sellerID uuid.UUID
//   - startPrice int64
//   - duration time.Duration
func (_e *AuctionRepository_Expecter) Create(ctx interface{}, itemID interface{}, sellerID interface{}, startPrice interface{}, duration interface{}) *AuctionRepository_Create_Call {
	return &AuctionRepository_Create_Call{Call: _e.mock.On("Create", ctx, itemID, sellerID, startPrice, duration)}
}

func (_c *AuctionRepository_Create_Call) Run(run func(ctx context.Context, itemID uuid.UUID, sellerID uuid.UUID, startPrice int64, duration time.Duration)) *AuctionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int64), args[4].(time.Duration))
	})
	return _c
}

func (_c *AuctionRepository_Create_Call) Return(_a0 *domain.Auction, _a1 error) *AuctionRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionRepository_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int64, time.Duration) (*domain.Auction, error)) *AuctionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FinalizeExpiredAuction provides a mock function with given fields: ctx, auctionID
func (_m *AuctionRepository) FinalizeExpiredAuction(ctx context.Context, auctionID uuid.UUID) error {
	ret := _m.Called(ctx, auctionID)

	if len(ret) == 0 {
		panic("no return value specified for FinalizeExpiredAuction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, auctionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuctionRepository_FinalizeExpiredAuction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinalizeExpiredAuction'
type AuctionRepository_FinalizeExpiredAuction_Call struct {
	*mock.Call
}

// FinalizeExpiredAuction is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID uuid.UUID
func (_e *AuctionRepository_Expecter) FinalizeExpiredAuction(ctx interface{}, auctionID interface{}) *AuctionRepository_FinalizeExpiredAuction_Call {
	return &AuctionRepository_FinalizeExpiredAuction_Call{Call: _e.mock.On("FinalizeExpiredAuction", ctx, auctionID)}
}

func (_c *AuctionRepository_FinalizeExpiredAuction_Call) Run(run func(ctx context.Context, auctionID uuid.UUID)) *AuctionRepository_FinalizeExpiredAuction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AuctionRepository_FinalizeExpiredAuction_Call) Return(_a0 error) *AuctionRepository_FinalizeExpiredAuction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuctionRepository_FinalizeExpiredAuction_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *AuctionRepository_FinalizeExpiredAuction_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *AuctionRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Auction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Auction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Auction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Auction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Auction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type AuctionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *AuctionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *AuctionRepository_GetByID_Call {
	return &AuctionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *AuctionRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *AuctionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AuctionRepository_GetByID_Call) Return(_a0 *domain.Auction, _a1 error) *AuctionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Auction, error)) *AuctionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListActive provides a mock function with given fields: ctx, limit, offset
func (_m *AuctionRepository) ListActive(ctx context.Context, limit int32, offset int32) ([]*domain.Auction, int64, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListActive")
	}

	var r0 []*domain.Auction
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) ([]*domain.Auction, int64, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) []*domain.Auction); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Auction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) int64); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int32, int32) error); ok {
		r2 = rf(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AuctionRepository_ListActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActive'
type AuctionRepository_ListActive_Call struct {
	*mock.Call
}

// ListActive is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int32
//   - offset int32
func (_e *AuctionRepository_Expecter) ListActive(ctx interface{}, limit interface{}, offset interface{}) *AuctionRepository_ListActive_Call {
	return &AuctionRepository_ListActive_Call{Call: _e.mock.On("ListActive", ctx, limit, offset)}
}

func (_c *AuctionRepository_ListActive_Call) Run(run func(ctx context.Context, limit int32, offset int32)) *AuctionRepository_ListActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *AuctionRepository_ListActive_Call) Return(_a0 []*domain.Auction, _a1 int64, _a2 error) *AuctionRepository_ListActive_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *AuctionRepository_ListActive_Call) RunAndReturn(run func(context.Context, int32, int32) ([]*domain.Auction, int64, error)) *AuctionRepository_ListActive_Call {
	_c.Call.Return(run)
	return _c
}

// PlaceBidTransaction provides a mock function with given fields: ctx, auctionID, bidderID, amount, extendedEndTime
func (_m *AuctionRepository) PlaceBidTransaction(ctx context.Context, auctionID uuid.UUID, bidderID uuid.UUID, amount int64, extendedEndTime time.Time) error {
	ret := _m.Called(ctx, auctionID, bidderID, amount, extendedEndTime)

	if len(ret) == 0 {
		panic("no return value specified for PlaceBidTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int64, time.Time) error); ok {
		r0 = rf(ctx, auctionID, bidderID, amount, extendedEndTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuctionRepository_PlaceBidTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaceBidTransaction'
type AuctionRepository_PlaceBidTransaction_Call struct {
	*mock.Call
}

// PlaceBidTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID uuid.UUID
//   - bidderID uuid.UUID
//   - amount int64
//   - extendedEndTime time.Time
func (_e *AuctionRepository_Expecter) PlaceBidTransaction(ctx interface{}, auctionID interface{}, bidderID interface{}, amount interface{}, extendedEndTime interface{}) *AuctionRepository_PlaceBidTransaction_Call {
	return &AuctionRepository_PlaceBidTransaction_Call{Call: _e.mock.On("PlaceBidTransaction", ctx, auctionID, bidderID, amount, extendedEndTime)}
}

func (_c *AuctionRepository_PlaceBidTransaction_Call) Run(run func(ctx context.Context, auctionID uuid.UUID, bidderID uuid.UUID, amount int64, extendedEndTime time.Time)) *AuctionRepository_PlaceBidTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int64), args[4].(time.Time))
	})
	return _c
}

func (_c *AuctionRepository_PlaceBidTransaction_Call) Return(_a0 error) *AuctionRepository_PlaceBidTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuctionRepository_PlaceBidTransaction_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int64, time.Time) error) *AuctionRepository_PlaceBidTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuctionRepository creates a new instance of AuctionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuctionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuctionRepository {
	mock := &AuctionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
