// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/kiarashAlizadeh/herotech/internal/dto"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// GuildService is an autogenerated mock type for the GuildService type
type GuildService struct {
	mock.Mock
}

type GuildService_Expecter struct {
	mock *mock.Mock
}

func (_m *GuildService) EXPECT() *GuildService_Expecter {
	return &GuildService_Expecter{mock: &_m.Mock}
}

// CreateGuild provides a mock function with given fields: ctx, req
func (_m *GuildService) CreateGuild(ctx context.Context, req dto.CreateGuildRequest) (*dto.GuildResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateGuild")
	}

	var r0 *dto.GuildResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateGuildRequest) (*dto.GuildResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateGuildRequest) *dto.GuildResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GuildResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateGuildRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GuildService_CreateGuild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGuild'
type GuildService_CreateGuild_Call struct {
	*mock.Call
}

// CreateGuild is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.CreateGuildRequest
func (_e *GuildService_Expecter) CreateGuild(ctx interface{}, req interface{}) *GuildService_CreateGuild_Call {
	return &GuildService_CreateGuild_Call{Call: _e.mock.On("CreateGuild", ctx, req)}
}

func (_c *GuildService_CreateGuild_Call) Run(run func(ctx context.Context, req dto.CreateGuildRequest)) *GuildService_CreateGuild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateGuildRequest))
	})
	return _c
}

func (_c *GuildService_CreateGuild_Call) Return(_a0 *dto.GuildResponse, _a1 error) *GuildService_CreateGuild_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GuildService_CreateGuild_Call) RunAndReturn(run func(context.Context, dto.CreateGuildRequest) (*dto.GuildResponse, error)) *GuildService_CreateGuild_Call {
	_c.Call.Return(run)
	return _c
}

// DepositGold provides a mock function with given fields: ctx, id, req
func (_m *GuildService) DepositGold(ctx context.Context, id uuid.UUID, req dto.DepositGoldRequest) (*dto.GuildResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for DepositGold")
	}

	var r0 *dto.GuildResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.DepositGoldRequest) (*dto.GuildResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.DepositGoldRequest) *dto.GuildResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GuildResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.DepositGoldRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GuildService_DepositGold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DepositGold'
type GuildService_DepositGold_Call struct {
	*mock.Call
}

// DepositGold is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - req dto.DepositGoldRequest
func (_e *GuildService_Expecter) DepositGold(ctx interface{}, id interface{}, req interface{}) *GuildService_DepositGold_Call {
	return &GuildService_DepositGold_Call{Call: _e.mock.On("DepositGold", ctx, id, req)}
}

func (_c *GuildService_DepositGold_Call) Run(run func(ctx context.Context, id uuid.UUID, req dto.DepositGoldRequest)) *GuildService_DepositGold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(dto.DepositGoldRequest))
	})
	return _c
}

func (_c *GuildService_DepositGold_Call) Return(_a0 *dto.GuildResponse, _a1 error) *GuildService_DepositGold_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GuildService_DepositGold_Call) RunAndReturn(run func(context.Context, uuid.UUID, dto.DepositGoldRequest) (*dto.GuildResponse, error)) *GuildService_DepositGold_Call {
	_c.Call.Return(run)
	return _c
}

// GetGuild provides a mock function with given fields: ctx, id
func (_m *GuildService) GetGuild(ctx context.Context, id uuid.UUID) (*dto.GuildResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetGuild")
	}

	var r0 *dto.GuildResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.GuildResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.GuildResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GuildResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GuildService_GetGuild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGuild'
type GuildService_GetGuild_Call struct {
	*mock.Call
}

// GetGuild is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *GuildService_Expecter) GetGuild(ctx interface{}, id interface{}) *GuildService_GetGuild_Call {
	return &GuildService_GetGuild_Call{Call: _e.mock.On("GetGuild", ctx, id)}
}

func (_c *GuildService_GetGuild_Call) Run(run func(ctx context.Context, id uuid.UUID)) *GuildService_GetGuild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *GuildService_GetGuild_Call) Return(_a0 *dto.GuildResponse, _a1 error) *GuildService_GetGuild_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GuildService_GetGuild_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*dto.GuildResponse, error)) *GuildService_GetGuild_Call {
	_c.Call.Return(run)
	return _c
}

// GetWalletSummary provides a mock function with given fields: ctx, id
func (_m *GuildService) GetWalletSummary(ctx context.Context, id uuid.UUID) (*dto.WalletSummaryResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletSummary")
	}

	var r0 *dto.WalletSummaryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.WalletSummaryResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.WalletSummaryResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WalletSummaryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GuildService_GetWalletSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWalletSummary'
type GuildService_GetWalletSummary_Call struct {
	*mock.Call
}

// GetWalletSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *GuildService_Expecter) GetWalletSummary(ctx interface{}, id interface{}) *GuildService_GetWalletSummary_Call {
	return &GuildService_GetWalletSummary_Call{Call: _e.mock.On("GetWalletSummary", ctx, id)}
}

func (_c *GuildService_GetWalletSummary_Call) Run(run func(ctx context.Context, id uuid.UUID)) *GuildService_GetWalletSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *GuildService_GetWalletSummary_Call) Return(_a0 *dto.WalletSummaryResponse, _a1 error) *GuildService_GetWalletSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GuildService_GetWalletSummary_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*dto.WalletSummaryResponse, error)) *GuildService_GetWalletSummary_Call {
	_c.Call.Return(run)
	return _c
}

// ListGuilds provides a mock function with given fields: ctx, req
func (_m *GuildService) ListGuilds(ctx context.Context, req dto.PaginationRequest) (*dto.PaginatedResponse[dto.GuildResponse], error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListGuilds")
	}

	var r0 *dto.PaginatedResponse[dto.GuildResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.PaginationRequest) (*dto.PaginatedResponse[dto.GuildResponse], error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.PaginationRequest) *dto.PaginatedResponse[dto.GuildResponse]); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PaginatedResponse[dto.GuildResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.PaginationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GuildService_ListGuilds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGuilds'
type GuildService_ListGuilds_Call struct {
	*mock.Call
}

// ListGuilds is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.PaginationRequest
func (_e *GuildService_Expecter) ListGuilds(ctx interface{}, req interface{}) *GuildService_ListGuilds_Call {
	return &GuildService_ListGuilds_Call{Call: _e.mock.On("ListGuilds", ctx, req)}
}

func (_c *GuildService_ListGuilds_Call) Run(run func(ctx context.Context, req dto.PaginationRequest)) *GuildService_ListGuilds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.PaginationRequest))
	})
	return _c
}

func (_c *GuildService_ListGuilds_Call) Return(_a0 *dto.PaginatedResponse[dto.GuildResponse], _a1 error) *GuildService_ListGuilds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GuildService_ListGuilds_Call) RunAndReturn(run func(context.Context, dto.PaginationRequest) (*dto.PaginatedResponse[dto.GuildResponse], error)) *GuildService_ListGuilds_Call {
	_c.Call.Return(run)
	return _c
}

// NewGuildService creates a new instance of GuildService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGuildService(t interface {
	mock.TestingT
	Cleanup(func())
}) *GuildService {
	mock := &GuildService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
