// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kiarashAlizadeh/herotech/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// GuildRepository is an autogenerated mock type for the GuildRepository type
type GuildRepository struct {
	mock.Mock
}

type GuildRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *GuildRepository) EXPECT() *GuildRepository_Expecter {
	return &GuildRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, name, dailyLimit
func (_m *GuildRepository) Create(ctx context.Context, name string, dailyLimit int64) (*domain.Guild, error) {
	ret := _m.Called(ctx, name, dailyLimit)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Guild
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (*domain.Guild, error)); ok {
		return rf(ctx, name, dailyLimit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) *domain.Guild); ok {
		r0 = rf(ctx, name, dailyLimit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Guild)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, name, dailyLimit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GuildRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type GuildRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - dailyLimit int64
func (_e *GuildRepository_Expecter) Create(ctx interface{}, name interface{}, dailyLimit interface{}) *GuildRepository_Create_Call {
	return &GuildRepository_Create_Call{Call: _e.mock.On("Create", ctx, name, dailyLimit)}
}

func (_c *GuildRepository_Create_Call) Run(run func(ctx context.Context, name string, dailyLimit int64)) *GuildRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *GuildRepository_Create_Call) Return(_a0 *domain.Guild, _a1 error) *GuildRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GuildRepository_Create_Call) RunAndReturn(run func(context.Context, string, int64) (*domain.Guild, error)) *GuildRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DepositGold provides a mock function with given fields: ctx, id, amount
func (_m *GuildRepository) DepositGold(ctx context.Context, id uuid.UUID, amount int64) (*domain.Guild, error) {
	ret := _m.Called(ctx, id, amount)

	if len(ret) == 0 {
		panic("no return value specified for DepositGold")
	}

	var r0 *domain.Guild
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) (*domain.Guild, error)); ok {
		return rf(ctx, id, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) *domain.Guild); ok {
		r0 = rf(ctx, id, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Guild)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64) error); ok {
		r1 = rf(ctx, id, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GuildRepository_DepositGold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DepositGold'
type GuildRepository_DepositGold_Call struct {
	*mock.Call
}

// DepositGold is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - amount int64
func (_e *GuildRepository_Expecter) DepositGold(ctx interface{}, id interface{}, amount interface{}) *GuildRepository_DepositGold_Call {
	return &GuildRepository_DepositGold_Call{Call: _e.mock.On("DepositGold", ctx, id, amount)}
}

func (_c *GuildRepository_DepositGold_Call) Run(run func(ctx context.Context, id uuid.UUID, amount int64)) *GuildRepository_DepositGold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int64))
	})
	return _c
}

func (_c *GuildRepository_DepositGold_Call) Return(_a0 *domain.Guild, _a1 error) *GuildRepository_DepositGold_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GuildRepository_DepositGold_Call) RunAndReturn(run func(context.Context, uuid.UUID, int64) (*domain.Guild, error)) *GuildRepository_DepositGold_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *GuildRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Guild, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Guild
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Guild, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Guild); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Guild)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GuildRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type GuildRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *GuildRepository_Expecter) GetByID(ctx interface{}, id interface{}) *GuildRepository_GetByID_Call {
	return &GuildRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *GuildRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *GuildRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *GuildRepository_GetByID_Call) Return(_a0 *domain.Guild, _a1 error) *GuildRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GuildRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Guild, error)) *GuildRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetWallet provides a mock function with given fields: ctx, id
func (_m *GuildRepository) GetWallet(ctx context.Context, id uuid.UUID) (int64, int64, int64, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWallet")
	}

	var r0 int64
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, int64, int64, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) int64); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) int64); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, uuid.UUID) error); ok {
		r3 = rf(ctx, id)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GuildRepository_GetWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWallet'
type GuildRepository_GetWallet_Call struct {
	*mock.Call
}

// GetWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *GuildRepository_Expecter) GetWallet(ctx interface{}, id interface{}) *GuildRepository_GetWallet_Call {
	return &GuildRepository_GetWallet_Call{Call: _e.mock.On("GetWallet", ctx, id)}
}

func (_c *GuildRepository_GetWallet_Call) Run(run func(ctx context.Context, id uuid.UUID)) *GuildRepository_GetWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *GuildRepository_GetWallet_Call) Return(total int64, reserved int64, available int64, err error) *GuildRepository_GetWallet_Call {
	_c.Call.Return(total, reserved, available, err)
	return _c
}

func (_c *GuildRepository_GetWallet_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int64, int64, int64, error)) *GuildRepository_GetWallet_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *GuildRepository) List(ctx context.Context, limit int32, offset int32) ([]*domain.Guild, int64, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Guild
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) ([]*domain.Guild, int64, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) []*domain.Guild); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Guild)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) int64); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int32, int32) error); ok {
		r2 = rf(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GuildRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type GuildRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int32
//   - offset int32
func (_e *GuildRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *GuildRepository_List_Call {
	return &GuildRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *GuildRepository_List_Call) Run(run func(ctx context.Context, limit int32, offset int32)) *GuildRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *GuildRepository_List_Call) Return(_a0 []*domain.Guild, _a1 int64, _a2 error) *GuildRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *GuildRepository_List_Call) RunAndReturn(run func(context.Context, int32, int32) ([]*domain.Guild, int64, error)) *GuildRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewGuildRepository creates a new instance of GuildRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGuildRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GuildRepository {
	mock := &GuildRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
