// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kiarashAlizadeh/herotech/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ItemRepository is an autogenerated mock type for the ItemRepository type
type ItemRepository struct {
	mock.Mock
}

type ItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ItemRepository) EXPECT() *ItemRepository_Expecter {
	return &ItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, name, itemType, ownerID, basePrice
func (_m *ItemRepository) Create(ctx context.Context, name string, itemType domain.ItemType, ownerID uuid.UUID, basePrice int64) (*domain.Item, error) {
	ret := _m.Called(ctx, name, itemType, ownerID, basePrice)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.ItemType, uuid.UUID, int64) (*domain.Item, error)); ok {
		return rf(ctx, name, itemType, ownerID, basePrice)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.ItemType, uuid.UUID, int64) *domain.Item); ok {
		r0 = rf(ctx, name, itemType, ownerID, basePrice)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.ItemType, uuid.UUID, int64) error); ok {
		r1 = rf(ctx, name, itemType, ownerID, basePrice)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - itemType domain.ItemType
//   - ownerID uuid.UUID
//   - basePrice int64
func (_e *ItemRepository_Expecter) Create(ctx interface{}, name interface{}, itemType interface{}, ownerID interface{}, basePrice interface{}) *ItemRepository_Create_Call {
	return &ItemRepository_Create_Call{Call: _e.mock.On("Create", ctx, name, itemType, ownerID, basePrice)}
}

func (_c *ItemRepository_Create_Call) Run(run func(ctx context.Context, name string, itemType domain.ItemType, ownerID uuid.UUID, basePrice int64)) *ItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.ItemType), args[3].(uuid.UUID), args[4].(int64))
	})
	return _c
}

func (_c *ItemRepository_Create_Call) Return(_a0 *domain.Item, _a1 error) *ItemRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemRepository_Create_Call) RunAndReturn(run func(context.Context, string, domain.ItemType, uuid.UUID, int64) (*domain.Item, error)) *ItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ItemRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Item, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Item, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Item); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ItemRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ItemRepository_Expecter) GetByID(ctx interface{}, id interface{}) *ItemRepository_GetByID_Call {
	return &ItemRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ItemRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ItemRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ItemRepository_GetByID_Call) Return(_a0 *domain.Item, _a1 error) *ItemRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Item, error)) *ItemRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByOwner provides a mock function with given fields: ctx, ownerID
func (_m *ItemRepository) GetByOwner(ctx context.Context, ownerID uuid.UUID) ([]*domain.Item, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByOwner")
	}

	var r0 []*domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Item, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Item); ok {
		r0 = rf(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemRepository_GetByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOwner'
type ItemRepository_GetByOwner_Call struct {
	*mock.Call
}

// GetByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID uuid.UUID
func (_e *ItemRepository_Expecter) GetByOwner(ctx interface{}, ownerID interface{}) *ItemRepository_GetByOwner_Call {
	return &ItemRepository_GetByOwner_Call{Call: _e.mock.On("GetByOwner", ctx, ownerID)}
}

func (_c *ItemRepository_GetByOwner_Call) Run(run func(ctx context.Context, ownerID uuid.UUID)) *ItemRepository_GetByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ItemRepository_GetByOwner_Call) Return(_a0 []*domain.Item, _a1 error) *ItemRepository_GetByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemRepository_GetByOwner_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.Item, error)) *ItemRepository_GetByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// ListAvailable provides a mock function with given fields: ctx, itemType, limit, offset
func (_m *ItemRepository) ListAvailable(ctx context.Context, itemType *domain.ItemType, limit int32, offset int32) ([]*domain.Item, int64, error) {
	ret := _m.Called(ctx, itemType, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailable")
	}

	var r0 []*domain.Item
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ItemType, int32, int32) ([]*domain.Item, int64, error)); ok {
		return rf(ctx, itemType, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ItemType, int32, int32) []*domain.Item); ok {
		r0 = rf(ctx, itemType, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.ItemType, int32, int32) int64); ok {
		r1 = rf(ctx, itemType, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *domain.ItemType, int32, int32) error); ok {
		r2 = rf(ctx, itemType, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ItemRepository_ListAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAvailable'
type ItemRepository_ListAvailable_Call struct {
	*mock.Call
}

// ListAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - itemType *domain.ItemType
//   - limit int32
//   - offset int32
func (_e *ItemRepository_Expecter) ListAvailable(ctx interface{}, itemType interface{}, limit interface{}, offset interface{}) *ItemRepository_ListAvailable_Call {
	return &ItemRepository_ListAvailable_Call{Call: _e.mock.On("ListAvailable", ctx, itemType, limit, offset)}
}

func (_c *ItemRepository_ListAvailable_Call) Run(run func(ctx context.Context, itemType *domain.ItemType, limit int32, offset int32)) *ItemRepository_ListAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.ItemType), args[2].(int32), args[3].(int32))
	})
	return _c
}

func (_c *ItemRepository_ListAvailable_Call) Return(_a0 []*domain.Item, _a1 int64, _a2 error) *ItemRepository_ListAvailable_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ItemRepository_ListAvailable_Call) RunAndReturn(run func(context.Context, *domain.ItemType, int32, int32) ([]*domain.Item, int64, error)) *ItemRepository_ListAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// ListForSale provides a mock function with given fields: ctx, itemID, listPrice
func (_m *ItemRepository) ListForSale(ctx context.Context, itemID uuid.UUID, listPrice int64) error {
	ret := _m.Called(ctx, itemID, listPrice)

	if len(ret) == 0 {
		panic("no return value specified for ListForSale")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) error); ok {
		r0 = rf(ctx, itemID, listPrice)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ItemRepository_ListForSale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForSale'
type ItemRepository_ListForSale_Call struct {
	*mock.Call
}

// ListForSale is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID uuid.UUID
//   - listPrice int64
func (_e *ItemRepository_Expecter) ListForSale(ctx interface{}, itemID interface{}, listPrice interface{}) *ItemRepository_ListForSale_Call {
	return &ItemRepository_ListForSale_Call{Call: _e.mock.On("ListForSale", ctx, itemID, listPrice)}
}

func (_c *ItemRepository_ListForSale_Call) Run(run func(ctx context.Context, itemID uuid.UUID, listPrice int64)) *ItemRepository_ListForSale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int64))
	})
	return _c
}

func (_c *ItemRepository_ListForSale_Call) Return(_a0 error) *ItemRepository_ListForSale_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ItemRepository_ListForSale_Call) RunAndReturn(run func(context.Context, uuid.UUID, int64) error) *ItemRepository_ListForSale_Call {
	_c.Call.Return(run)
	return _c
}

// PurchaseLimitOrder provides a mock function with given fields: ctx, itemID, buyerID
func (_m *ItemRepository) PurchaseLimitOrder(ctx context.Context, itemID uuid.UUID, buyerID uuid.UUID) error {
	ret := _m.Called(ctx, itemID, buyerID)

	if len(ret) == 0 {
		panic("no return value specified for PurchaseLimitOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, itemID, buyerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ItemRepository_PurchaseLimitOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurchaseLimitOrder'
type ItemRepository_PurchaseLimitOrder_Call struct {
	*mock.Call
}

// PurchaseLimitOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID uuid.UUID
//   - buyerID uuid.UUID
func (_e *ItemRepository_Expecter) PurchaseLimitOrder(ctx interface{}, itemID interface{}, buyerID interface{}) *ItemRepository_PurchaseLimitOrder_Call {
	return &ItemRepository_PurchaseLimitOrder_Call{Call: _e.mock.On("PurchaseLimitOrder", ctx, itemID, buyerID)}
}

func (_c *ItemRepository_PurchaseLimitOrder_Call) Run(run func(ctx context.Context, itemID uuid.UUID, buyerID uuid.UUID)) *ItemRepository_PurchaseLimitOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ItemRepository_PurchaseLimitOrder_Call) Return(_a0 error) *ItemRepository_PurchaseLimitOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ItemRepository_PurchaseLimitOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *ItemRepository_PurchaseLimitOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewItemRepository creates a new instance of ItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemRepository {
	mock := &ItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
