// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/kiarashAlizadeh/herotech/internal/dto"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ItemService is an autogenerated mock type for the ItemService type
type ItemService struct {
	mock.Mock
}

type ItemService_Expecter struct {
	mock *mock.Mock
}

func (_m *ItemService) EXPECT() *ItemService_Expecter {
	return &ItemService_Expecter{mock: &_m.Mock}
}

// BuyItemDirectly provides a mock function with given fields: ctx, itemID, buyerID
func (_m *ItemService) BuyItemDirectly(ctx context.Context, itemID uuid.UUID, buyerID uuid.UUID) error {
	ret := _m.Called(ctx, itemID, buyerID)

	if len(ret) == 0 {
		panic("no return value specified for BuyItemDirectly")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, itemID, buyerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ItemService_BuyItemDirectly_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuyItemDirectly'
type ItemService_BuyItemDirectly_Call struct {
	*mock.Call
}

// BuyItemDirectly is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID uuid.UUID
//   - buyerID uuid.UUID
func (_e *ItemService_Expecter) BuyItemDirectly(ctx interface{}, itemID interface{}, buyerID interface{}) *ItemService_BuyItemDirectly_Call {
	return &ItemService_BuyItemDirectly_Call{Call: _e.mock.On("BuyItemDirectly", ctx, itemID, buyerID)}
}

func (_c *ItemService_BuyItemDirectly_Call) Run(run func(ctx context.Context, itemID uuid.UUID, buyerID uuid.UUID)) *ItemService_BuyItemDirectly_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ItemService_BuyItemDirectly_Call) Return(_a0 error) *ItemService_BuyItemDirectly_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ItemService_BuyItemDirectly_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *ItemService_BuyItemDirectly_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function with given fields: ctx, id
func (_m *ItemService) GetItem(ctx context.Context, id uuid.UUID) (*dto.ItemResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 *dto.ItemResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.ItemResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.ItemResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ItemResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemService_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type ItemService_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ItemService_Expecter) GetItem(ctx interface{}, id interface{}) *ItemService_GetItem_Call {
	return &ItemService_GetItem_Call{Call: _e.mock.On("GetItem", ctx, id)}
}

func (_c *ItemService_GetItem_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ItemService_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ItemService_GetItem_Call) Return(_a0 *dto.ItemResponse, _a1 error) *ItemService_GetItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemService_GetItem_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*dto.ItemResponse, error)) *ItemService_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// ListAvailable provides a mock function with given fields: ctx, itemType, req
func (_m *ItemService) ListAvailable(ctx context.Context, itemType *string, req dto.PaginationRequest) (*dto.PaginatedResponse[dto.ItemResponse], error) {
	ret := _m.Called(ctx, itemType, req)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailable")
	}

	var r0 *dto.PaginatedResponse[dto.ItemResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string, dto.PaginationRequest) (*dto.PaginatedResponse[dto.ItemResponse], error)); ok {
		return rf(ctx, itemType, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string, dto.PaginationRequest) *dto.PaginatedResponse[dto.ItemResponse]); ok {
		r0 = rf(ctx, itemType, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PaginatedResponse[dto.ItemResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string, dto.PaginationRequest) error); ok {
		r1 = rf(ctx, itemType, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemService_ListAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAvailable'
type ItemService_ListAvailable_Call struct {
	*mock.Call
}

// ListAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - itemType *string
//   - req dto.PaginationRequest
func (_e *ItemService_Expecter) ListAvailable(ctx interface{}, itemType interface{}, req interface{}) *ItemService_ListAvailable_Call {
	return &ItemService_ListAvailable_Call{Call: _e.mock.On("ListAvailable", ctx, itemType, req)}
}

func (_c *ItemService_ListAvailable_Call) Run(run func(ctx context.Context, itemType *string, req dto.PaginationRequest)) *ItemService_ListAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*string), args[2].(dto.PaginationRequest))
	})
	return _c
}

func (_c *ItemService_ListAvailable_Call) Return(_a0 *dto.PaginatedResponse[dto.ItemResponse], _a1 error) *ItemService_ListAvailable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemService_ListAvailable_Call) RunAndReturn(run func(context.Context, *string, dto.PaginationRequest) (*dto.PaginatedResponse[dto.ItemResponse], error)) *ItemService_ListAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// ListItem provides a mock function with given fields: ctx, ownerID, req
func (_m *ItemService) ListItem(ctx context.Context, ownerID uuid.UUID, req dto.CreateItemRequest) (*dto.ItemResponse, error) {
	ret := _m.Called(ctx, ownerID, req)

	if len(ret) == 0 {
		panic("no return value specified for ListItem")
	}

	var r0 *dto.ItemResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateItemRequest) (*dto.ItemResponse, error)); ok {
		return rf(ctx, ownerID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateItemRequest) *dto.ItemResponse); ok {
		r0 = rf(ctx, ownerID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ItemResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.CreateItemRequest) error); ok {
		r1 = rf(ctx, ownerID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ItemService_ListItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItem'
type ItemService_ListItem_Call struct {
	*mock.Call
}

// ListItem is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID uuid.UUID
//   - req dto.CreateItemRequest
func (_e *ItemService_Expecter) ListItem(ctx interface{}, ownerID interface{}, req interface{}) *ItemService_ListItem_Call {
	return &ItemService_ListItem_Call{Call: _e.mock.On("ListItem", ctx, ownerID, req)}
}

func (_c *ItemService_ListItem_Call) Run(run func(ctx context.Context, ownerID uuid.UUID, req dto.CreateItemRequest)) *ItemService_ListItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(dto.CreateItemRequest))
	})
	return _c
}

func (_c *ItemService_ListItem_Call) Return(_a0 *dto.ItemResponse, _a1 error) *ItemService_ListItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ItemService_ListItem_Call) RunAndReturn(run func(context.Context, uuid.UUID, dto.CreateItemRequest) (*dto.ItemResponse, error)) *ItemService_ListItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewItemService creates a new instance of ItemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemService {
	mock := &ItemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
