// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auctions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeAuction = `-- name: CloseAuction :one
UPDATE auctions
SET status = $2,
    winner_id = $3
WHERE id = $1
RETURNING id, item_id, seller_id, status, start_price, highest_bid, winner_id, ends_at, created_at
`

type CloseAuctionParams struct {
	ID       uuid.UUID
	Status   AuctionStatus
	WinnerID pgtype.UUID
}

// Terminate the auction lifecycle, finalizing the status and sealing the winner
func (q *Queries) CloseAuction(ctx context.Context, arg CloseAuctionParams) (Auction, error) {
	row := q.db.QueryRow(ctx, closeAuction, arg.ID, arg.Status, arg.WinnerID)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SellerID,
		&i.Status,
		&i.StartPrice,
		&i.HighestBid,
		&i.WinnerID,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const countActiveAuctions = `-- name: CountActiveAuctions :one
SELECT COUNT(*) FROM auctions
WHERE status = 'active'
`

func (q *Queries) CountActiveAuctions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAuctions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveAuctionsBySeller = `-- name: CountActiveAuctionsBySeller :one
SELECT COUNT(*) FROM auctions
WHERE seller_id = $1 AND status = 'active'
`

// Guard rail query to verify a guild hasn't bypassed the limit of 5 concurrent active auctions
func (q *Queries) CountActiveAuctionsBySeller(ctx context.Context, sellerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAuctionsBySeller, sellerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuction = `-- name: CreateAuction :one
INSERT INTO auctions (item_id, seller_id, start_price, ends_at)
VALUES ($1, $2, $3, $4)
RETURNING id, item_id, seller_id, status, start_price, highest_bid, winner_id, ends_at, created_at
`

type CreateAuctionParams struct {
	ItemID     uuid.UUID
	SellerID   uuid.UUID
	StartPrice int64
	EndsAt     pgtype.Timestamptz
}

func (q *Queries) CreateAuction(ctx context.Context, arg CreateAuctionParams) (Auction, error) {
	row := q.db.QueryRow(ctx, createAuction,
		arg.ItemID,
		arg.SellerID,
		arg.StartPrice,
		arg.EndsAt,
	)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SellerID,
		&i.Status,
		&i.StartPrice,
		&i.HighestBid,
		&i.WinnerID,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuction = `-- name: GetAuction :one
SELECT id, item_id, seller_id, status, start_price, highest_bid, winner_id, ends_at, created_at FROM auctions WHERE id = $1
`

func (q *Queries) GetAuction(ctx context.Context, id uuid.UUID) (Auction, error) {
	row := q.db.QueryRow(ctx, getAuction, id)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SellerID,
		&i.Status,
		&i.StartPrice,
		&i.HighestBid,
		&i.WinnerID,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuctionForUpdate = `-- name: GetAuctionForUpdate :one
SELECT id, item_id, seller_id, status, start_price, highest_bid, winner_id, ends_at, created_at FROM auctions WHERE id = $1 FOR UPDATE
`

// Lock the active auction state to safely evaluate incoming bids sequentially
func (q *Queries) GetAuctionForUpdate(ctx context.Context, id uuid.UUID) (Auction, error) {
	row := q.db.QueryRow(ctx, getAuctionForUpdate, id)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SellerID,
		&i.Status,
		&i.StartPrice,
		&i.HighestBid,
		&i.WinnerID,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAuctions = `-- name: ListActiveAuctions :many
SELECT a.id, a.item_id, a.seller_id, a.status, a.start_price, a.highest_bid, a.winner_id, a.ends_at, a.created_at, i.name as item_name, i.type as item_type
FROM auctions a
JOIN items i ON a.item_id = i.id
WHERE a.status = 'active'
ORDER BY a.ends_at ASC
LIMIT $1 OFFSET $2
`

type ListActiveAuctionsParams struct {
	Limit  int32
	Offset int32
}

type ListActiveAuctionsRow struct {
	ID         uuid.UUID
	ItemID     uuid.UUID
	SellerID   uuid.UUID
	Status     AuctionStatus
	StartPrice int64
	HighestBid pgtype.Int8
	WinnerID   pgtype.UUID
	EndsAt     pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	ItemName   string
	ItemType   ItemType
}

// Fetch all live auctions with embedded core item metadata for the storefront
func (q *Queries) ListActiveAuctions(ctx context.Context, arg ListActiveAuctionsParams) ([]ListActiveAuctionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAuctions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAuctionsRow{}
	for rows.Next() {
		var i ListActiveAuctionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.SellerID,
			&i.Status,
			&i.StartPrice,
			&i.HighestBid,
			&i.WinnerID,
			&i.EndsAt,
			&i.CreatedAt,
			&i.ItemName,
			&i.ItemType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuctionBid = `-- name: UpdateAuctionBid :one
UPDATE auctions
SET highest_bid = $2,
    winner_id = $3,
    ends_at = $4
WHERE id = $1
RETURNING id, item_id, seller_id, status, start_price, highest_bid, winner_id, ends_at, created_at
`

type UpdateAuctionBidParams struct {
	ID         uuid.UUID
	HighestBid pgtype.Int8
	WinnerID   pgtype.UUID
	EndsAt     pgtype.Timestamptz
}

// Update the current leading bid, record the frontrunner, and apply potential time extensions
func (q *Queries) UpdateAuctionBid(ctx context.Context, arg UpdateAuctionBidParams) (Auction, error) {
	row := q.db.QueryRow(ctx, updateAuctionBid,
		arg.ID,
		arg.HighestBid,
		arg.WinnerID,
		arg.EndsAt,
	)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SellerID,
		&i.Status,
		&i.StartPrice,
		&i.HighestBid,
		&i.WinnerID,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}
