// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bids.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createBid = `-- name: CreateBid :one
INSERT INTO bids (auction_id, bidder_id, amount, is_active)
VALUES ($1, $2, $3, TRUE)
RETURNING id, auction_id, bidder_id, amount, is_active, created_at
`

type CreateBidParams struct {
	AuctionID uuid.UUID
	BidderID  uuid.UUID
	Amount    int64
}

func (q *Queries) CreateBid(ctx context.Context, arg CreateBidParams) (Bid, error) {
	row := q.db.QueryRow(ctx, createBid, arg.AuctionID, arg.BidderID, arg.Amount)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.AuctionID,
		&i.BidderID,
		&i.Amount,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateAuctionBids = `-- name: DeactivateAuctionBids :many
UPDATE bids
SET is_active = FALSE
WHERE auction_id = $1
RETURNING id, auction_id, bidder_id, amount, is_active, created_at
`

// Bulk invalidate all remaining active bids once an auction reaches its final conclusion
func (q *Queries) DeactivateAuctionBids(ctx context.Context, auctionID uuid.UUID) ([]Bid, error) {
	rows, err := q.db.Query(ctx, deactivateAuctionBids, auctionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bid{}
	for rows.Next() {
		var i Bid
		if err := rows.Scan(
			&i.ID,
			&i.AuctionID,
			&i.BidderID,
			&i.Amount,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deactivateBid = `-- name: DeactivateBid :one
UPDATE bids
SET is_active = FALSE
WHERE id = $1
RETURNING id, auction_id, bidder_id, amount, is_active, created_at
`

// Flag a bid as inactive when it is outbid or manually retracted by the user
func (q *Queries) DeactivateBid(ctx context.Context, id uuid.UUID) (Bid, error) {
	row := q.db.QueryRow(ctx, deactivateBid, id)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.AuctionID,
		&i.BidderID,
		&i.Amount,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveBidByBidder = `-- name: GetActiveBidByBidder :one
SELECT id, auction_id, bidder_id, amount, is_active, created_at FROM bids 
WHERE auction_id = $1 AND bidder_id = $2 AND is_active = TRUE
`

type GetActiveBidByBidderParams struct {
	AuctionID uuid.UUID
	BidderID  uuid.UUID
}

func (q *Queries) GetActiveBidByBidder(ctx context.Context, arg GetActiveBidByBidderParams) (Bid, error) {
	row := q.db.QueryRow(ctx, getActiveBidByBidder, arg.AuctionID, arg.BidderID)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.AuctionID,
		&i.BidderID,
		&i.Amount,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getBidForUpdate = `-- name: GetBidForUpdate :one
SELECT id, auction_id, bidder_id, amount, is_active, created_at FROM bids WHERE id = $1 FOR UPDATE
`

// Lock a specific bid allocation during direct cancellations
func (q *Queries) GetBidForUpdate(ctx context.Context, id uuid.UUID) (Bid, error) {
	row := q.db.QueryRow(ctx, getBidForUpdate, id)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.AuctionID,
		&i.BidderID,
		&i.Amount,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
