// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guilds.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countGuilds = `-- name: CountGuilds :one
SELECT COUNT(*) FROM guilds
`

func (q *Queries) CountGuilds(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGuilds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuild = `-- name: CreateGuild :one
INSERT INTO guilds (name, daily_limit)
VALUES ($1, $2)
RETURNING id, name, gold_balance, daily_limit, created_at, updated_at
`

type CreateGuildParams struct {
	Name       string
	DailyLimit int64
}

// Register a new guild into the market with a baseline configuration
func (q *Queries) CreateGuild(ctx context.Context, arg CreateGuildParams) (Guild, error) {
	row := q.db.QueryRow(ctx, createGuild, arg.Name, arg.DailyLimit)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GoldBalance,
		&i.DailyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailySpent = `-- name: GetDailySpent :one
SELECT COALESCE(SUM(total_spent), 0)::BIGINT
FROM daily_purchases
WHERE guild_id = $1 AND date = CURRENT_DATE
`

// Fetch today's total accumulated spending to enforce the daily anti-monopoly quota
func (q *Queries) GetDailySpent(ctx context.Context, guildID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getDailySpent, guildID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getGuildByID = `-- name: GetGuildByID :one
SELECT id, name, gold_balance, daily_limit, created_at, updated_at FROM guilds
WHERE id = $1
`

func (q *Queries) GetGuildByID(ctx context.Context, id uuid.UUID) (Guild, error) {
	row := q.db.QueryRow(ctx, getGuildByID, id)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GoldBalance,
		&i.DailyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGuildByIDForUpdate = `-- name: GetGuildByIDForUpdate :one
SELECT id, name, gold_balance, daily_limit, created_at, updated_at FROM guilds
WHERE id = $1
FOR UPDATE
`

// Lock the guild row to safely mutate balance and prevent race conditions during checkout or bidding
func (q *Queries) GetGuildByIDForUpdate(ctx context.Context, id uuid.UUID) (Guild, error) {
	row := q.db.QueryRow(ctx, getGuildByIDForUpdate, id)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GoldBalance,
		&i.DailyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletSummary = `-- name: GetWalletSummary :one
SELECT
    g.gold_balance                                          AS total_balance,
    COALESCE(SUM(b.amount) FILTER (WHERE b.is_active), 0)::BIGINT  AS reserved_amount,
    (g.gold_balance - COALESCE(SUM(b.amount) FILTER (WHERE b.is_active), 0)::BIGINT)::BIGINT AS available_balance
FROM guilds g
LEFT JOIN bids b ON b.bidder_id = g.id
WHERE g.id = $1
GROUP BY g.id, g.gold_balance
`

type GetWalletSummaryRow struct {
	TotalBalance     int64
	ReservedAmount   int64
	AvailableBalance int64
}

// Calculate a complete financial snapshot for a guild, isolating active bid reservations
func (q *Queries) GetWalletSummary(ctx context.Context, id uuid.UUID) (GetWalletSummaryRow, error) {
	row := q.db.QueryRow(ctx, getWalletSummary, id)
	var i GetWalletSummaryRow
	err := row.Scan(&i.TotalBalance, &i.ReservedAmount, &i.AvailableBalance)
	return i, err
}

const listGuilds = `-- name: ListGuilds :many
SELECT id, name, gold_balance, daily_limit, created_at, updated_at FROM guilds 
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListGuildsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListGuilds(ctx context.Context, arg ListGuildsParams) ([]Guild, error) {
	rows, err := q.db.Query(ctx, listGuilds, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Guild{}
	for rows.Next() {
		var i Guild
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GoldBalance,
			&i.DailyLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuildBalance = `-- name: UpdateGuildBalance :one
UPDATE guilds
SET
    gold_balance = gold_balance + $2,
    updated_at   = NOW()
WHERE id = $1
  AND gold_balance + $2 >= 0
RETURNING id, name, gold_balance, daily_limit, created_at, updated_at
`

type UpdateGuildBalanceParams struct {
	ID          uuid.UUID
	GoldBalance int64
}

// Adjust the guild's gold balance. The WHERE clause acts as a safety guard against negative balances
func (q *Queries) UpdateGuildBalance(ctx context.Context, arg UpdateGuildBalanceParams) (Guild, error) {
	row := q.db.QueryRow(ctx, updateGuildBalance, arg.ID, arg.GoldBalance)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GoldBalance,
		&i.DailyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDailyPurchase = `-- name: UpsertDailyPurchase :one
INSERT INTO daily_purchases (guild_id, date, total_spent)
VALUES ($1, CURRENT_DATE, $2)
ON CONFLICT (guild_id, date) 
DO UPDATE SET total_spent = daily_purchases.total_spent + EXCLUDED.total_spent
RETURNING guild_id, date, total_spent
`

type UpsertDailyPurchaseParams struct {
	GuildID    uuid.UUID
	TotalSpent int64
}

// Log or increment the guild's daily expenditures inside the current calendar date
func (q *Queries) UpsertDailyPurchase(ctx context.Context, arg UpsertDailyPurchaseParams) (DailyPurchase, error) {
	row := q.db.QueryRow(ctx, upsertDailyPurchase, arg.GuildID, arg.TotalSpent)
	var i DailyPurchase
	err := row.Scan(&i.GuildID, &i.Date, &i.TotalSpent)
	return i, err
}
