// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAvailableItems = `-- name: CountAvailableItems :one
SELECT COUNT(*) FROM items
WHERE status = 'available'
`

func (q *Queries) CountAvailableItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAvailableItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAvailableItemsByType = `-- name: CountAvailableItemsByType :one
SELECT COUNT(*) FROM items
WHERE status = 'available'
  AND type = $1
`

func (q *Queries) CountAvailableItemsByType(ctx context.Context, type_ ItemType) (int64, error) {
	row := q.db.QueryRow(ctx, countAvailableItemsByType, type_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (name, type, owner_id, base_price, list_price, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, type, status, owner_id, base_price, list_price, created_at, updated_at
`

type CreateItemParams struct {
	Name      string
	Type      ItemType
	OwnerID   uuid.UUID
	BasePrice int64
	ListPrice pgtype.Int8
	Status    ItemStatus
}

// Mint a newly listed item into the marketplace registry
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Name,
		arg.Type,
		arg.OwnerID,
		arg.BasePrice,
		arg.ListPrice,
		arg.Status,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.OwnerID,
		&i.BasePrice,
		&i.ListPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, name, type, status, owner_id, base_price, list_price, created_at, updated_at FROM items
WHERE id = $1
`

func (q *Queries) GetItemByID(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.OwnerID,
		&i.BasePrice,
		&i.ListPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemByIDForUpdate = `-- name: GetItemByIDForUpdate :one
SELECT id, name, type, status, owner_id, base_price, list_price, created_at, updated_at FROM items
WHERE id = $1
FOR UPDATE
`

// Lock the asset to prevent double-selling or concurrent auction setups on the same item
func (q *Queries) GetItemByIDForUpdate(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByIDForUpdate, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.OwnerID,
		&i.BasePrice,
		&i.ListPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAvailableItems = `-- name: ListAvailableItems :many
SELECT id, name, type, status, owner_id, base_price, list_price, created_at, updated_at FROM items
WHERE status = 'available'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAvailableItemsParams struct {
	Limit  int32
	Offset int32
}

// Retrieve all unmarketed items up for grabs, sorted by recent listings
func (q *Queries) ListAvailableItems(ctx context.Context, arg ListAvailableItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listAvailableItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.OwnerID,
			&i.BasePrice,
			&i.ListPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableItemsByType = `-- name: ListAvailableItemsByType :many
SELECT id, name, type, status, owner_id, base_price, list_price, created_at, updated_at FROM items
WHERE status = 'available'
  AND type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAvailableItemsByTypeParams struct {
	Type   ItemType
	Limit  int32
	Offset int32
}

func (q *Queries) ListAvailableItemsByType(ctx context.Context, arg ListAvailableItemsByTypeParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listAvailableItemsByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.OwnerID,
			&i.BasePrice,
			&i.ListPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transferItemOwnership = `-- name: TransferItemOwnership :one
UPDATE items
SET
    owner_id   = $2,
    status     = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, type, status, owner_id, base_price, list_price, created_at, updated_at
`

type TransferItemOwnershipParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Status  ItemStatus
}

// Atomically shift asset ownership and update status when an order completes or auction closes
func (q *Queries) TransferItemOwnership(ctx context.Context, arg TransferItemOwnershipParams) (Item, error) {
	row := q.db.QueryRow(ctx, transferItemOwnership, arg.ID, arg.OwnerID, arg.Status)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.OwnerID,
		&i.BasePrice,
		&i.ListPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateItemStatus = `-- name: UpdateItemStatus :one
UPDATE items
SET
    status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, type, status, owner_id, base_price, list_price, created_at, updated_at
`

type UpdateItemStatusParams struct {
	ID     uuid.UUID
	Status ItemStatus
}

func (q *Queries) UpdateItemStatus(ctx context.Context, arg UpdateItemStatusParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItemStatus, arg.ID, arg.Status)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.OwnerID,
		&i.BasePrice,
		&i.ListPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
