// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuctionStatus string

const (
	AuctionStatusActive    AuctionStatus = "active"
	AuctionStatusEnded     AuctionStatus = "ended"
	AuctionStatusCancelled AuctionStatus = "cancelled"
)

func (e *AuctionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuctionStatus(s)
	case string:
		*e = AuctionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AuctionStatus: %T", src)
	}
	return nil
}

type NullAuctionStatus struct {
	AuctionStatus AuctionStatus
	Valid         bool // Valid is true if AuctionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuctionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AuctionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuctionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuctionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuctionStatus), nil
}

type ItemStatus string

const (
	ItemStatusAvailable ItemStatus = "available"
	ItemStatusInAuction ItemStatus = "in_auction"
	ItemStatusSold      ItemStatus = "sold"
)

func (e *ItemStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemStatus(s)
	case string:
		*e = ItemStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemStatus: %T", src)
	}
	return nil
}

type NullItemStatus struct {
	ItemStatus ItemStatus
	Valid      bool // Valid is true if ItemStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ItemStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemStatus), nil
}

type ItemType string

const (
	ItemTypeCommon    ItemType = "common"
	ItemTypeRare      ItemType = "rare"
	ItemTypeLegendary ItemType = "legendary"
)

func (e *ItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemType(s)
	case string:
		*e = ItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemType: %T", src)
	}
	return nil
}

type NullItemType struct {
	ItemType ItemType
	Valid    bool // Valid is true if ItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemType) Scan(value interface{}) error {
	if value == nil {
		ns.ItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemType), nil
}

type TransactionType string

const (
	TransactionTypeDeposit  TransactionType = "deposit"
	TransactionTypePurchase TransactionType = "purchase"
	TransactionTypeReserve  TransactionType = "reserve"
	TransactionTypeRelease  TransactionType = "release"
	TransactionTypeRefund   TransactionType = "refund"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType
	Valid           bool // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type Auction struct {
	ID         uuid.UUID
	ItemID     uuid.UUID
	SellerID   uuid.UUID
	Status     AuctionStatus
	StartPrice int64
	HighestBid pgtype.Int8
	WinnerID   pgtype.UUID
	EndsAt     pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Bid struct {
	ID        uuid.UUID
	AuctionID uuid.UUID
	BidderID  uuid.UUID
	Amount    int64
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

type DailyPurchase struct {
	GuildID    uuid.UUID
	Date       pgtype.Date
	TotalSpent int64
}

type Guild struct {
	ID          uuid.UUID
	Name        string
	GoldBalance int64
	DailyLimit  int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Item struct {
	ID        uuid.UUID
	Name      string
	Type      ItemType
	Status    ItemStatus
	OwnerID   uuid.UUID
	BasePrice int64
	ListPrice pgtype.Int8
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type WalletTransaction struct {
	ID          uuid.UUID
	GuildID     uuid.UUID
	Type        TransactionType
	Amount      int64
	ReferenceID pgtype.UUID
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}
