// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Terminate the auction lifecycle, finalizing the status and sealing the winner
	CloseAuction(ctx context.Context, arg CloseAuctionParams) (Auction, error)
	CountActiveAuctions(ctx context.Context) (int64, error)
	// Guard rail query to verify a guild hasn't bypassed the limit of 5 concurrent active auctions
	CountActiveAuctionsBySeller(ctx context.Context, sellerID uuid.UUID) (int64, error)
	CountAvailableItems(ctx context.Context) (int64, error)
	CountAvailableItemsByType(ctx context.Context, type_ ItemType) (int64, error)
	CountGuilds(ctx context.Context) (int64, error)
	CreateAuction(ctx context.Context, arg CreateAuctionParams) (Auction, error)
	CreateBid(ctx context.Context, arg CreateBidParams) (Bid, error)
	// Register a new guild into the market with a baseline configuration
	CreateGuild(ctx context.Context, arg CreateGuildParams) (Guild, error)
	// Mint a newly listed item into the marketplace registry
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	// Bulk invalidate all remaining active bids once an auction reaches its final conclusion
	DeactivateAuctionBids(ctx context.Context, auctionID uuid.UUID) ([]Bid, error)
	// Flag a bid as inactive when it is outbid or manually retracted by the user
	DeactivateBid(ctx context.Context, id uuid.UUID) (Bid, error)
	GetActiveBidByBidder(ctx context.Context, arg GetActiveBidByBidderParams) (Bid, error)
	GetAuction(ctx context.Context, id uuid.UUID) (Auction, error)
	// Lock the active auction state to safely evaluate incoming bids sequentially
	GetAuctionForUpdate(ctx context.Context, id uuid.UUID) (Auction, error)
	// Lock a specific bid allocation during direct cancellations
	GetBidForUpdate(ctx context.Context, id uuid.UUID) (Bid, error)
	// Fetch today's total accumulated spending to enforce the daily anti-monopoly quota
	GetDailySpent(ctx context.Context, guildID uuid.UUID) (int64, error)
	GetGuildByID(ctx context.Context, id uuid.UUID) (Guild, error)
	// Lock the guild row to safely mutate balance and prevent race conditions during checkout or bidding
	GetGuildByIDForUpdate(ctx context.Context, id uuid.UUID) (Guild, error)
	GetItemByID(ctx context.Context, id uuid.UUID) (Item, error)
	// Lock the asset to prevent double-selling or concurrent auction setups on the same item
	GetItemByIDForUpdate(ctx context.Context, id uuid.UUID) (Item, error)
	// Retrieve all items owned by a specific guild to populate their inventory profile
	GetItemsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Item, error)
	// Calculate a complete financial snapshot for a guild, isolating active bid reservations
	GetWalletSummary(ctx context.Context, id uuid.UUID) (GetWalletSummaryRow, error)
	// Fetch all live auctions with embedded core item metadata for the storefront
	ListActiveAuctions(ctx context.Context, arg ListActiveAuctionsParams) ([]ListActiveAuctionsRow, error)
	// Retrieve all unmarketed items up for grabs, sorted by recent listings
	ListAvailableItems(ctx context.Context, arg ListAvailableItemsParams) ([]Item, error)
	ListAvailableItemsByType(ctx context.Context, arg ListAvailableItemsByTypeParams) ([]Item, error)
	ListGuilds(ctx context.Context, arg ListGuildsParams) ([]Guild, error)
	// Extract the full financial audit ledger for a specific guild, reverse chronological order
	ListWalletTransactions(ctx context.Context, guildID uuid.UUID) ([]WalletTransaction, error)
	// Append an immutable audit trail entry for every shift in guild finances
	LogWalletTransaction(ctx context.Context, arg LogWalletTransactionParams) (WalletTransaction, error)
	// Atomically shift asset ownership and update status when an order completes or auction closes
	TransferItemOwnership(ctx context.Context, arg TransferItemOwnershipParams) (Item, error)
	// Update the current leading bid, record the frontrunner, and apply potential time extensions
	UpdateAuctionBid(ctx context.Context, arg UpdateAuctionBidParams) (Auction, error)
	// Adjust the guild's gold balance. The WHERE clause acts as a safety guard against negative balances
	UpdateGuildBalance(ctx context.Context, arg UpdateGuildBalanceParams) (Guild, error)
	UpdateItemStatus(ctx context.Context, arg UpdateItemStatusParams) (Item, error)
	// Log or increment the guild's daily expenditures inside the current calendar date
	UpsertDailyPurchase(ctx context.Context, arg UpsertDailyPurchaseParams) (DailyPurchase, error)
}

var _ Querier = (*Queries)(nil)
