// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet_transactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT id, guild_id, type, amount, reference_id, description, created_at FROM wallet_transactions
WHERE guild_id = $1
ORDER BY created_at DESC
`

// Extract the full financial audit ledger for a specific guild, reverse chronological order
func (q *Queries) ListWalletTransactions(ctx context.Context, guildID uuid.UUID) ([]WalletTransaction, error) {
	rows, err := q.db.Query(ctx, listWalletTransactions, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletTransaction{}
	for rows.Next() {
		var i WalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Type,
			&i.Amount,
			&i.ReferenceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logWalletTransaction = `-- name: LogWalletTransaction :one
INSERT INTO wallet_transactions (guild_id, type, amount, reference_id, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, guild_id, type, amount, reference_id, description, created_at
`

type LogWalletTransactionParams struct {
	GuildID     uuid.UUID
	Type        TransactionType
	Amount      int64
	ReferenceID pgtype.UUID
	Description pgtype.Text
}

// Append an immutable audit trail entry for every shift in guild finances
func (q *Queries) LogWalletTransaction(ctx context.Context, arg LogWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, logWalletTransaction,
		arg.GuildID,
		arg.Type,
		arg.Amount,
		arg.ReferenceID,
		arg.Description,
	)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Type,
		&i.Amount,
		&i.ReferenceID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
