package service

import "errors"

var (
	ErrAuctionNotFound        = errors.New("target live auction could not be found")
	ErrItemAlreadyInAuction   = errors.New("this item is already listed in another active auction")
	ErrBidTooLow              = errors.New("bid must be at least 5% higher than the current standing position")
	ErrAuctionNotActive       = errors.New("auction is no longer accepting bids")
	ErrBidOnOwnAuction        = errors.New("cannot bid on your own auction item")
	ErrInsufficientBalance    = errors.New("insufficient available gold balance to back reservation")
	ErrRetractLeadingBid      = errors.New("cannot retract a bid while holding the leading position")
	ErrActiveBidNotFound      = errors.New("no active bid reservation found to cancel")
	ErrAssociatedItemNotFound = errors.New("associated item listing not found")
	ErrNonLegendaryAuction    = errors.New("only legendary tier items can access the auction house platform")
	ErrNotItemOwner           = errors.New("unauthorized action: asset ownership mismatch")
	ErrMaxActiveAuctions      = errors.New("guild has reached maximum concurrent active auctions limit")
	ErrInvalidAuctionID       = errors.New("invalid auction id")
	ErrGuildNotFound          = errors.New("guild not found")
	ErrEmptyGuildName         = errors.New("guild name cannot be empty")
	ErrInvalidGuildID         = errors.New("invalid guild id")
	ErrItemNotFound           = errors.New("requested market item does not exist")
	ErrItemNotAvailable       = errors.New("item is no longer available for direct purchase")
	ErrPurchaseOwnItem        = errors.New("cannot purchase your own listed item")
	ErrInsufficientGold       = errors.New("insufficient available gold balance")
	ErrDailyLimitExceeded     = errors.New("purchase violates daily transaction limit")
	ErrInvalidListPrice       = errors.New("common and rare items require a positive fixed listing price")
	ErrBlankItemName          = errors.New("item catalog name cannot be blank")
	ErrLegendaryPriceAllowed  = errors.New("legendary tier items pass through auctions only and cannot hold a listing price")
	ErrInvalidEntityIDs       = errors.New("provided transaction entity ids are invalid")
	ErrInvalidGuildNameLength = errors.New("guild name must be between 2 and 100 characters")
	ErrInvalidDailyLimit      = errors.New("guild daily limit must be greater than zero")
	ErrGuildNameExists        = errors.New("guild name already exists")
	ErrInvalidItemNameLength  = errors.New("item name must be between 2 and 100 characters")
	ErrInvalidItemType        = errors.New("item type must be one of: common, rare, legendary")
	ErrInvalidStartPrice      = errors.New("auction start price must be greater than zero")
	ErrInvalidDuration        = errors.New("auction duration must be greater than zero")
	ErrInvalidBidAmount       = errors.New("bid amount must be greater than zero")
	ErrAlreadyHighestBidder   = errors.New("you are already holding the leading position in this auction")
	ErrInvalidDepositAmount   = errors.New("deposit amount must be greater than zero")
)
